apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::222396745666:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1F2Z6KK1EEEK2
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
